use crate::simulator::Config;
use core::future::Future;
use sealed::Sealed;

#[cfg(any(feature = "embassy", feature = "std"))]
pub use crate::rt_engine::traits::{
    EjectOutput, InjectInput, RtEngineInputChannel, RtEngineOutputChannel,
};

/// Trait that defines the methods that a DEVS event bag set must implement.
///
/// # Safety
///
/// This trait must be implemented via macros. Do not implement it manually.
pub unsafe trait Bag {
    /// Build a new instance of the bag.
    fn build() -> Self;

    /// Returns `true` if the ports are empty.
    fn is_empty(&self) -> bool;

    /// Clears the ports, removing all values.
    fn clear(&mut self);
}

/// Trait that defines the type inside of a Bag for rt_engine enums.
///
/// # Safety
///
/// This trait is implemented internally. Do not implement it manually.
pub trait AsPort: Bag + Sealed {
    /// The type of the values contained in the bag.
    type Item;
}

/// Trait that defines a type that maps to event bag ports.
/// Its main purpose is its usage by the `RtEngine` to inject and eject events from the model's ports.
///
/// # Safety
///
/// This trait must be implemented via macros. Do not implement it manually.
pub unsafe trait BagMux: Bag {
    /// The type that represents the ports of the model. Each variant corresponds to a port.
    type Mux;

    /// Maps the type to the corresponding port, allowing to inject events to the bag.
    fn inject_event(&mut self, event: Self::Mux) -> Result<(), Self::Mux>;

    /// Maps the type to the corresponding port, allowing to receive events from the bag.
    fn eject_events(&self, ejector: impl FnMut(Self::Mux));
}

/// Interface for DEVS components. All DEVS components must implement this trait.
pub trait Component {
    /// Input event bag of the model.
    type Input: Bag;

    /// Output event bag of the model.
    type Output: Bag;
}

/// Partial interface for DEVS atomic models.
/// It is used as a helper trait to implement the [`crate::Atomic`] trait.
///
/// # Safety
///
/// This trait must be implemented via macros. Do not implement it manually.
pub unsafe trait PartialAtomic: Component {
    /// The data type used to represent the state of the model.
    type State;
}

/// Partial interface for DEVS coupled models.
/// It is used as a helper trait to implement [`crate::Coupled`] trait.
///
/// # Safety
///
/// This trait must be implemented via macros. Do not implement it manually.
pub unsafe trait PartialCoupled: Component {
    /// Wrapper type holding all inner components' inputs.
    type ComponentsInput: Bag;

    /// Wrapper type holding all inner components' outputs.
    type ComponentsOutput: Bag;
}

/// Trait for handling time during a DEVS simulation.
///
/// In order to be able to simulate DEVS models, the simulator needs this trait to
/// keep track of time and the time of the next state transition of each component.
///
/// # Safety
///
/// This trait must be implemented via macros. Do not implement it manually.
pub unsafe trait SimTime {
    /// Returns the last time the component was updated.
    fn get_t_last(&self) -> f64;

    /// Sets the last time the component was updated.
    fn set_t_last(&mut self, t_last: f64);

    /// Returns the next time the component will be updated.
    fn get_t_next(&self) -> f64;

    /// Sets the next time the component will be updated.
    fn set_t_next(&mut self, t_next: f64);
}

/// Interface for simulating DEVS models. All DEVS models must implement this trait.
///
/// # Safety
///
/// This trait must be implemented via macros. Do not implement it manually.
pub unsafe trait AbstractSimulator: Component + SimTime {
    /// It starts the simulation, setting the initial time to t_start.
    /// It returns the time for the next state transition of the inner DEVS model.
    fn start(&mut self, t_start: f64) -> f64;

    /// It stops the simulation, setting the last time to t_stop.
    fn stop(&mut self, t_stop: f64);

    /// Executes output functions and propagates messages according to EOCs.
    /// Internally, it checks that the model is imminent before executing.
    fn lambda(&mut self, output: &mut Self::Output, t: f64);

    /// Propagates messages according to ICs and EICs, and executes state transition functions.
    /// Internally, it checks that the model is imminent before executing.
    /// Finally, it returns the time for the next state transition of the inner DEVS model.
    fn delta(&mut self, input: &mut Self::Input, output: &mut Self::Output, t: f64) -> f64;
}

/// Interface for handling input events in an asynchronous DEVS simulation.
///
/// Unlike other traits, this trait must be implemented by the user, as it is not generated by macros.
/// It allows the model to handle input events asynchronously, waiting for external events without blocking the simulation.
pub trait AsyncInput {
    /// Set this to the input event bag type of your model under study.
    type Input: Bag;

    /// Handles input events asynchronously.
    ///
    /// It receives the time interval `[t_from, t_until]` and a mutable reference to the input event bag.
    /// It returns the time of the next event, which is usually the time of the next state transition.
    /// If an external event occurs, it should inject the event to the input and return the time at which the event happened.
    fn handle(
        &mut self,
        config: &Config,
        t_from: f64,
        t_until: f64,
        input: &mut Self::Input,
    ) -> impl Future<Output = f64>;
}

pub(crate) mod sealed {
    /// Trait used to prevent users from implementing certain traits manually.
    pub trait Sealed {}
}
