// Auto-generated by devstone_generator. Do not edit by hand.
    use std::time::Instant;
    use xdevs::Component;

    extern crate alloc;

    fn main() {
        const WIDTH: usize = 400;
        const W: usize = WIDTH - 1;

        let start = Instant::now();

        xdevs::generate_ho!(400, 400);

        let generator = xdevs::devstone::common::JobGenerator::new(5);

        let top_model: xdevs::devstone::ho::TopModel<W> = xdevs::devstone::ho::TopModel::build(generator, model_ho);
        let duration = start.elapsed();
        println!("Model creation time: {:?}", duration);
        let start = Instant::now();
        let mut simulator = top_model.to_simulator();
        let config = xdevs::simulation::Config::new(0.0, 10.0, 1.0, None);
        let duration = start.elapsed();
        println!("Simulator creation time: {:?}", duration);
        let start = Instant::now();
        simulator.simulate_vt(&config);
        let duration = start.elapsed();
        println!("Simulation time: {:?}", duration);
    }
    